#!/bin/bash

#$1: command to run
#$2: expected error level. By default = 0
#$3: rollback action in case of error.

function launch {
    error=$2
    if [ -z "$error" ]; then
        error=0
    fi  

    cmd=${1:-"pwd"}
    echo "command: ${cmd}"
    eval $cmd
    errorlevel=$?
    if [ "$errorlevel" -ne "$error" ]; then
        echo "Error executing: $cmd"
        echo "Errorlevel: $errorlevel"
    
        if [ -n "$3" ]; then
            cmd=${3:-"pwd"}
            echo "fail command: ${cmd}"
            eval $cmd
        fi  
        exit $errorlevel;
    fi  
}

iscsiadm=`which iscsiadm`
dd=`which dd`

# This default value works for a 1Gigabit network and a Sata disk
bs="4K"

if [ ! -f "$iscsiadm" ]; then
	echo "[!] iscsiadm not found! You must install openiscsi"
	echo "[+] Try run: yum install iscsi-initiator-utils"
fi

if [ ! -f "$dd" ]; then
	echo "[!] dd not found! You must install coreutils"
	echo "[+] Try run: yum install coreutils"
fi

if [ $# -lt 5 ]; then
	echo "[+] Usage: `basename $0` MODE storage_ip iqn file_path iscsi_address [volume_size]"
	exit 254
fi

mode=$1
ip=$2
iqn=$3
file=$4
path=$5
size=$6

$iscsiadm -m node -T "$iqn" -p "$ip" -u
$iscsiadm -m node -T "$iqn" -p "$ip" -l

if [ $? != 0 ]; then
    $iscsiadm  -m discovery -t st -p "$ip"
    if [ $? != 0 ]; then
        echo "[!] Error running discovery on $ip"
        exit 255
    fi

    $iscsiadm -m node -T "$iqn" -p "$ip" -u
    $iscsiadm -m node -T "$iqn" -p "$ip" -l

    if [ $? != 0 ]; then
        echo "[!] Error running loggin to $ip:$iqn"
        exit 255
    fi
fi


# We wait while the system assigns the device (/dev/sdx) 
sleep 2

iqnfile=/dev/disk/by-path/$path

# file => iqn
if [ "$mode" == "deploy" ]; then
    if [ ! -f "$file" ]; then
        echo "[!] Source file not found!"
        exit 1
    fi

    launch "$dd bs=$bs if=\"$file\" of=\"$iqnfile\""

    if [ $? != 0 ]; then
        echo "[!] $mode: Error clonning $file to $ip:$iqn"
        exit 2
    fi
# iqn => file
elif [ "$mode" == "bundle" ]; then
    if [ -f "$file" ]; then
        echo "[!] File already exist"
        exit 3
    fi

    if [ -z $size ]; then
        launch "$dd bs=\"$bs\" if=\"$iqnfile\" of=\"$file\""
    else
        launch "$dd ibs=1024 count=\"$size\" if=\"$iqnfile\" of=\"$file\""
    fi
    if [ $? != 0 ]; then
        echo "[!] $mode: Error clonning $ip:$iqn to $file"
        exit 4
    fi
fi

$iscsiadm -m node -T "$iqn" -p "$ip" -u
